spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intaddblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 13201230

logging:
  level:
    root: info
    com.inta: debug
  file:
    path: log/blog-dev.log

server:
  port: 8081

mybatis:
  type-aliases-package: cn.inta.intaddblog.po
  mapper-locations: cn.inta.intaddblog.mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





