spring:
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /img/avatar.png




